# Merge NHANES 2013-2018 datasets

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(car)
#library(dplyr)
library(readr)
library(DataExplorer)
library(tableone)
library(Publish)
library(jtools)
require(mice)
```

## Analytic dataset

### Load 2013-18 datasets

```{r, cache=TRUE}
load("data/analytic13recoded.RData")
load("data/analytic15recoded.RData")
load("data/analytic17recoded.RData")
```

### Merge 2013-18 datasets

```{r, cache=TRUE}
# adults aged 20 years or more
data.merged0 <- rbind(analytic13, analytic15, analytic17)
dim(data.merged0)
data.merged <- droplevels(data.merged0)
```

### Check missingness

```{r, cache=TRUE}
plot_missing(data.merged)
# profile_missing(data.merged)
dim(data.merged)
data.complete <- na.omit(data.merged)
dim(data.complete)
data.merged.x <- data.merged[!is.na(data.merged["obese"]),]
dim(data.merged.x)
data.merged.xy <- data.merged.x[!is.na(data.merged.x["diabetes"]),]
dim(data.merged.xy)
plot_missing(data.merged.xy)
imp1 <- mice(data.merged.xy, m = 1, maxit = 10, method = "pmm")
densityplot(imp1)
data.imputed <- complete(imp1, action = 1)
dim(data.imputed)
```

### Summary statistics

```{r, cache=TRUE}
round(prop.table(table(data.complete$obese))*100, 2)

vars <- c(
  # Demographic
  "age", "age.cat", "sex", "education", "race", 
  "marital", "income", "born", 
  
  # Diabetes history
  "diabetes.family.history",
  
  # Smoking
  "smoking", 
  
  # Diet
  "diet.healthy", 

  # Physical activity
  "physical.activity", 
  
  # Access to routine healthcare
  "medical.access",
  
  # Blood pressure and Hypertension
  "systolicBP", "diastolicBP", 
  
  # Sleep 
  "sleep",

  # Laboratory 
  "uric.acid", "protein.total", "bilirubin.total", "phosphorus",
  "sodium", "potassium", "globulin", "calcium.total", 
  "high.cholesterol",
  
  # Survey year
  "year"
)
tab1 <- CreateTableOne(vars = vars, 
                       strata = "obese", 
                       data = data.complete, 
                       test = FALSE, 
                       addOverall = TRUE)
print(tab1, 
      showAllLevels = TRUE, 
      smd = TRUE)
```

## Proxy data from ICD10 codes

```{r, cache=TRUE}
dat.proxy.long <- rbind(rx2013, rx2015, rx2017) 
dat.proxy.long$icd10 <- NULL

# Rename 3 digits ICD-10 codes as icd10
colnames(dat.proxy.long)[names(dat.proxy.long)=="icd10.new"] <- "icd10"

# Delete codes associated with exposure and outcome
dat.proxy.long <- subset(dat.proxy.long, icd10 != "E66") # Overweight and obesity
dat.proxy.long <- subset(dat.proxy.long, icd10 != "O24") # Gestational diabetes mellitus
dat.proxy.long <- subset(dat.proxy.long, icd10 != "E10") # Type 1 diabetes mellitus
dat.proxy.long <- subset(dat.proxy.long, icd10 != "E11") # Type 2 diabetes mellitus
```

## Mortality data

Mortality data obtained from [2019 Public-Use Linked Mortality Files](https://ftp.cdc.gov/pub/Health_Statistics/NCHS/datalinkage/linked_mortality/)

### Mortality data 2013-14

```{r, cache=TRUE}
mort2013 <- read_fwf(file = "data/Mortalitydata/NHANES_2013_2014_MORT_2019_PUBLIC.dat",
                     col_types = "iiiiiiii",
                     fwf_cols(id = c(1,6),
                              mort_eligstat = c(15,15),
                              mort_stat = c(16,16),
                              mort_ucod_leading = c(17,19),
                              mort_diabetes = c(20,20),
                              mort_hyperten = c(21,21),
                              mort_permth_int = c(43,45),
                              mort_permth_exm = c(46,48)),
                     na = c("", "."))
```

### Mortality data 2015-16

```{r, cache=TRUE}
mort2015 <- read_fwf(file = "data/Mortalitydata/NHANES_2015_2016_MORT_2019_PUBLIC.dat",
                     col_types = "iiiiiiii",
                     fwf_cols(id = c(1,6),
                              mort_eligstat = c(15,15),
                              mort_stat = c(16,16),
                              mort_ucod_leading = c(17,19),
                              mort_diabetes = c(20,20),
                              mort_hyperten = c(21,21),
                              mort_permth_int = c(43,45),
                              mort_permth_exm = c(46,48)),
                     na = c("", "."))
```

### Mortality data 2017-18

```{r, cache=TRUE}
mort2017 <- read_fwf(file = "data/Mortalitydata/NHANES_2017_2018_MORT_2019_PUBLIC.dat",
                     col_types = "iiiiiiii",
                     fwf_cols(id = c(1,6),
                              mort_eligstat = c(15,15),
                              mort_stat = c(16,16),
                              mort_ucod_leading = c(17,19),
                              mort_diabetes = c(20,20),
                              mort_hyperten = c(21,21),
                              mort_permth_int = c(43,45),
                              mort_permth_exm = c(46,48)),
                     na = c("", "."))
```

### Merging mortality datasets

```{r, cache=TRUE}
dat.mortality <- rbind(mort2013, mort2015, mort2017)
table(dat.mortality$mort_eligstat, useNA = "always")
#1 = "Eligible"
#2 = "Under age 18, not available for public release"
#3 = "Ineligible"
```

## Save dataset for later use

```{r, cache=TRUE}
save(data.merged, 
     data.merged.xy, 
     data.imputed,
     data.complete, 
     dat.proxy.long, 
     dat.mortality, 
     file = "data/analytic3cycles.RData")
```
