# Plasmode Simulation


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(SASxport)
require(DiagrammeR)
require(DiagrammeRsvg)
require(rsvg)
library(magrittr)
library(svglite)
library(png)
require(nhanesA)
require(survey)
require(Publish)
require(jtools)
```

## Load data

```{r, cache=TRUE}
load(file = "data/fullData.RData") 
table(full.data$exposure)/sum(table(full.data$exposure))
table(full.data$outcome)/sum(table(full.data$outcome))
length(demovars)
demoform
length(labvars.original) 
labvars.originalform
length(labvars)
labform
length(sel.proxy)
sel.proxy.form
length(emp.cov.names)
basicdata <- full.data[,c("idx", 
                          demovars,
                          labvars.original)]
extendeddata <- full.data[,c("idx", 
                             demovars,
                             labvars.original,
                             emp.cov.names)]
```

## Create simple count variable

```{r, cache=TRUE}
full.data$simple.count <- apply(full.data[sel.proxy], 1, sum)
summary(full.data$simple.count)
hist(full.data$simple.count)
```

## Setup formulas

```{r, cache=TRUE}
rhsformula <- paste0(c(demoform, labform, "simple.count"), collapse = "+")
rhsformula
```

```{r init1, eval=TRUE, cache=TRUE}
formulaOut <- as.formula(paste0("outcome ~ exposure +", rhsformula))
formulaOut
```

## Initial plasmode

```{r, cache=TRUE}
require(Plasmode)
ss <- 7500
# from https://cran.r-project.org/src/contrib/Archive/Plasmode/Plasmode_0.1.0.tar.gz
simdata.obj0 <- PlasmodeBin(formulaOut,
                       data=full.data,
                       idVar="idx",
                       nsim=1, 
                       size=ss)
simdata.obj0$TrueOutBeta
length(simdata.obj0$TrueOutBeta)
simdata.obj0$RR
simdata.obj0$RD
```

## Plasmode simulation

```{r, cache=TRUE}
nSim <- 2000
simdata.obj <- PlasmodeBin(formulaOut,
                       data=full.data,
                       idVar="idx",
                       effectOR =2,
                       nsim=nSim, 
                       size=ss, 
                       eventRate=0.15, 
                       exposedPrev=0.40,
                       MMOut = c(rep(1, length(simdata.obj0$TrueOutBeta)-1)))
simdata.obj$TrueOutBeta
exp(simdata.obj$TrueOutBeta)
```

```{r, cache=TRUE}
simdata <- simdata.obj$Sim_Data 
```

## Save

```{r save, eval=TRUE, cache=TRUE}
save.image(file = "data/plasmode.RData")
```
